# Makefile for ContourModify
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = ContourModify.o
OUTPUT = ContourModify
LIBS= -lcontour.1 -lplot.1 -lpoly.1 -lrplot.1 -lfontdb.1 -lrfbuf.1 -lrxml.1 -lrcnv.1
SLIB=-lm
 


include $(MAKELIB).$(SYSTEM)
