# Makefile for XMLDecode
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLDecode.o
OUTPUT = XMLDecode
LIBS=-lrxml.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
