# Makefile for RCDFSize
# =====================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis -I$(CDF_PATH)/include
IGNVER=1
OBJS = RCDFSize.o
OUTPUT = RCDFSize
LIBS= -lrcdf.1 -L$(CDF_PATH)/lib -lcdf 
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
