# Makefile for oldraw
# =================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=rawopen.c rawclose.c rawread.c rawreadcurrent.c rawwrite.c rawseek.c raw.h lmt.h rawversions.h
OBJS=rawopen.o rawclose.o rawread.o rawreadcurrent.o rawwrite.o rawseek.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = oldraw


 

 















include $(MAKELIB).$(SYSTEM)
