# Makefile for OptionProcessFile
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionProcessFile.o
OUTPUT = OptionProcessFile
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
