# Makefile for XwinFrameBufferToXimage
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinFrameBufferToXimage.o
OUTPUT = XwinFrameBufferToXimage
LIBS=-lrfbuf.1  
XLIB=-lxwin.1
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
