# Makefile for TimeYMDHMSToJulian
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYMDHMSToJulian.o
OUTPUT = TimeYMDHMSToJulian
LIBS=-lrtime.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
