# Makefile for XwinOpenDisplay
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinOpenDisplay.o
OUTPUT = XwinOpenDisplay
LIBS=-lrfbuf.1 
XLIB=-lxwin.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
