# Makefile for xmltoppm
# =====================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=xmltoppm.c
OBJS = xmltoppm.o
SRC=hlpstr.h errstr.h xmltoppm.c
OBJS = xmltoppm.o
DSTPATH = $(BINPATH)
OUTPUT = xmltoppm
LIBS=-lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lpng -lm

include $(MAKEBIN).$(SYSTEM)
