# Makefile for tagdb library
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=tagdb.c
OBJS = tagdb.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = tagdb
LINK="1"

















include $(MAKELIB).$(SYSTEM)
