# Makefile for IGRFCall
# =====================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = IGRFCall.o
OUTPUT = IGRFCall
LIBS= -ligrf.1  
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
