# Makefile for xmltopng
# ======================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=xmltopng.c
OBJS = xmltopng.o
SRC=hlpstr.h errstr.h xmltopng.c
OBJS = xmltopng.o
DSTPATH = $(BINPATH)
OUTPUT = xmltopng
LIBS=-lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lpng -lm

include $(MAKEBIN).$(SYSTEM)
