# Makefile for FrameBufferFree
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferFree.o
OUTPUT = FrameBufferFree
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
