# Makefile for xmld
# =================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=xmld.c
OBJS = xmld.o
SRC=hlpstr.h errstr.h xmld.c
OBJS = xmld.o
DSTPATH = $(BINPATH)
OUTPUT = xmld
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lpng -lm 

include $(MAKEBIN).$(SYSTEM)
