# Makefile for tsg library
# ========================
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/superdarn

SRC  = maketsg.c 
OBJS = maketsg.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = tsg

include $(MAKELIB).$(SYSTEM)
