# Makefile for XwinCloseDisplay
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinCloseDisplay.o
OUTPUT = XwinCloseDisplay
LIBS=-lrfbuf.1 -lxwin.1 
SLIB=-lm
XLIB=-lxwin.1
 
include $(MAKELIB).$(SYSTEM)
