# Makefile for MapCircleClip
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = MapCircleClip.o
OUTPUT = MapCircleClip
LIBS= -lrmap.1 -lpoly.1 -lrplot.1 -lrfbuf.1 -lrxml.1 -lrcnv.1
SLIB=-lm
 





include $(MAKELIB).$(SYSTEM)
