# Makefile for binplotlib library
# ===============================
# by E.G.Thomas
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base

SRC = text_box.c

OBJS = text_box.o

INC = $(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = binplot
LINK="1"

include $(MAKELIB).$(SYSTEM)
