# Makefile for OptionFreeFile
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionFreeFile.o
OUTPUT = OptionFreeFile
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
