# Makefile for ConvertReadShort
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertReadShort.o
OUTPUT = ConvertReadShort
LIBS= -lrcnv.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
