# Makefile for time library
# =========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/general
SRC=time.c read.c
OBJS = time.o read.o
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = rtime
LINK="1"

















include $(MAKELIB).$(SYSTEM)
