# Makefile for cgi library
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=cgi.c
OBJS = cgi.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = rcgi
LINK="1"

















include $(MAKELIB).$(SYSTEM)
