# Makefile for eval library
# =========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/general
SRC=eval.c
OBJS = eval.o
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = reval
LINK="1"

















include $(MAKELIB).$(SYSTEM)
