# Makefile for FrameBufferMakeClip
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferMakeClip.o
OUTPUT = FrameBufferMakeClip
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
