# Makefile for OptionFreeText
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionFreeText.o
OUTPUT = OptionFreeText
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
