# Makefile for xml library
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=rxml.c call.c
OBJS = rxml.o call.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = rxml
LINK="1"

















include $(MAKELIB).$(SYSTEM)
