# Makefile for PostScriptPolygon
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptPolygon.o
OUTPUT = PostScriptPolygon
LIBS=-lrps.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
