site_name: RST Documentation
repo_url: https://github.com/superdarn/rst
theme: readthedocs
pages:
- Home: index.md
- About: about.md
- User-Guide:
        - install: user_guide/install.md
        - RST HOWTO: 
                - File Conversios:
                        - RAWACF to FITACF: user_guide/make_fit.md
                        - FITACF to GRID: user_guide/make_grid.md
                        - GRID to MAP: user_guide/map_grid.md
                - Plot Generation:
                        - time_plot: user_guide/time_plot.md 
- Reference Manual:
        - General:
                - Dmap Data: references/general/dmap_data.md
                - IQDAT Format: references/general/iqdat.md
                - RAWACF Format: references/general/rawacf.md
                - FITACF Format: references/general/fitacf.md
        - SuperDARN Tools:
                - make_fit: references/superdarn/tools/make_fit.md
                - make_grid: references/superdarn/tools/make_grid.md


