# Makefile for ACFex library
# ========================
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn -I$(USR_IPATH)/superdarn

SRC = acfex.c 
OBJS = acfex.o
INC=$(USR_IPATH)/superdarn
LINK="1"
DSTPATH=$(USR_LIBPATH)
OUTPUT = acfex
include $(MAKELIB).$(SYSTEM)









 

 















