# Makefile for pngd
# ==================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=pngd.c
OBJS = pngd.o
SRC=hlpstr.h errstr.h pngd.c
OBJS = pngd.o
DSTPATH = $(BINPATH)
OUTPUT = pngd
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lpng -lm 

 

include $(MAKEBIN).$(SYSTEM)
