# Makefile for OptionProcess
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionProcess.o
OUTPUT = OptionProcess
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
