# Makefile for ppmtoppmx
# ======================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
OBJS = ppmtoppmx.o
SRC=ppmtoppmx.c hlpstr.h errstr.h
DSTPATH = $(BINPATH)
OUTPUT = ppmtoppmx
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lpng -lm


 















include $(MAKEBIN).$(SYSTEM)
