MODULE IGRFDLM
DESCRIPTION IGRFDLM
VERSION 2.0
SOURCE R.J.Barnes, JHU/APL; Evan Thomas & Nathaniel Alden, Dartmouth College
BUILD_DATE October 2023
FUNCTION IGRFMODELCALL 7 7
FUNCTION IGRF_GETDATETIME 1 1 KEYWORDS
FUNCTION IGRF_SETDATETIME 1 6
FUNCTION IGRF_SETNOW 0 0
FUNCTION IGRF_TILT 6 6
FUNCTION IGRF_COMPUTE 1 1
FUNCTION ECDIP_CONVERT 6 6 KEYWORDS
FUNCTION ECDIP_MLT 7 7 KEYWORDS
