#  Makefile for mlt_v2 library
#  ===========================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis

SRC = mlt_v2.c
OBJS= mlt_v2.o

INC = $(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = mlt_v2
LINK="1"

include $(MAKELIB).$(SYSTEM)

