MODULE OLDCNVMAPDLM
DESCRIPTION OLDCNVMAPDLM
VERSION 1.0
SOURCE R.J.Barnes, JHU/APL
BUILD_DATE October 2010
FUNCTION OLDCNVMAPREAD 7 7
FUNCTION OLDCNVMAPWRITE 7 7
FUNCTION OLDCNVMAPLOADINX 2 2
FUNCTION OLDCNVMAPSEEK 7 8 KEYWORDS
FUNCTION OLDCNVMAPOPEN 1 1 KEYWORDS
FUNCTION OLDCNVMAPCLOSE 1 1





