# Makefile for PostScriptText
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptText.o
OUTPUT = PostScriptText
LIBS=-lrps.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
