# Makefile for FrameBufferCopy
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferCopy.o
OUTPUT = FrameBufferCopy
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
