# Makefile for FrameBufferRectangle
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferRectangle.o
OUTPUT = FrameBufferRectangle
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
