# Makefile for OptionScanFileArg
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionScanFileArg.o
OUTPUT = OptionScanFileArg
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
