# Makefile for invtime
# ====================
# Author: R.J.Barnes
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
OBJS = invtime.o
SRC=hlpstr.h errstr.h invtime.c
DSTPATH = $(BINPATH)
OUTPUT = invtime
LIBS =-lopt.1 -lrtime.1 
SLIB =-lm

 

 

include $(MAKEBIN).$(SYSTEM)
