# Makefile for oldgrid library
# =========================== 
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = oldreadgrid.c oldwritegrid.c 
OBJS = oldreadgrid.o oldwritegrid.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = oldgrd
 

 





include $(MAKELIB).$(SYSTEM)
