# Makefile for FrameBufferDBAdd
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = FrameBufferDBAdd.o
OUTPUT = FrameBufferDBAdd
LIBS=-limagedb.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
