# Makefile for idlsave library
# ============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis
SRC = idlsave.c 
OBJS = idlsave.o
INC=$(IPATH)/analysis
DSTPATH=$(LIBPATH)
LINK="1"
OUTPUT = idlsave

include $(MAKELIB).$(SYSTEM)
