# Makefile for PostScriptFreeClip
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptFreeClip.o
OUTPUT = PostScriptFreeClip
LIBS=-lrps.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
