# Makefile for scalexml
# =====================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=scalexml.c
OBJS = scalexml.o
SRC=hlpstr.h errstr.h scalexml.c
OBJS = scalexml.o
DSTPATH = $(BINPATH)
OUTPUT = scalexml
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lpng -lm

include $(MAKEBIN).$(SYSTEM)
