# Makefile for PostScriptRectangle
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptRectangle.o
OUTPUT = PostScriptRectangle
LIBS=-lrps.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
