# Makefile for ACF library
# ========================
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn 

SRC = acfcalculate.c average.c badlag.c normalize.c sumpower.c sumproduct.c
OBJS = acfcalculate.o average.o badlag.o normalize.o sumpower.o sumproduct.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = acf








 

 















include $(MAKELIB).$(SYSTEM)
