# Makefile for AACGMInit
# ======================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis
IGNVER=1 
OBJS = AACGMInit.o
OUTPUT = AACGMInit
LIBS= -laacgm.1  
SLIB=-lm
 





include $(MAKEBIN).$(SYSTEM)
