# # Makefile for OldFitClose
# # =======================
# # by R.J.Barnes
# #
# #

# INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
# IGNVER=1
# OBJS = OldFitClose.o
# OUTPUT = OldFitClose
include $(MAKECFG).$(SYSTEM)
LIBS=-loldfit.1 -lrtime.1 -ldmap.1 -lrcnv.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
