# Makefile for fft1
# =================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = fft1.o
OUTPUT = fft1
LIBS= -lrmath.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
