# Makefile for etime
# ==================
# Author: R.J.Barnes
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
DSTPATH = $(BINPATH)
OUTPUT = etime
OBJS=etime.o
SRC=hlpstr.h errstr.h etime.c
LIBS =-lopt.1 -lrtime.1
SLIB =-lm

 

 

include $(MAKEBIN).$(SYSTEM)
