# Makefile for OptionAdd
# ======================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionAdd.o
OUTPUT = OptionAdd
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
