# Makefile for poly
# =================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base

SRC=nrfit.c fft.c
OBJS =  nrfit.o fft.o
INC=$(IPATH)/base
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rmath


 

 





include $(MAKELIB).$(SYSTEM)
