# Makefile for RCDFMaxRecR
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis -I$(CDF_PATH)/include
IGNVER=1
OBJS = RCDFMaxRecR.o
OUTPUT = RCDFMaxRecR
LIBS= -lrcdf.1 -L$(CDF_PATH)/lib -lcdf 
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
