# Makefile for IGRFMagCmp
# =====================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = IGRFMagCmp.o
OUTPUT = IGRFMagCmp
LIBS= -ligrf.1  
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
