# Makefile for freq library
# ========================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/superdarn
SRC=freq.c
OBJS = freq.o
LINK="1"
INC=${IPATH}/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = freq
include $(MAKELIB).$(SYSTEM)










