# Makefile for sctnorm
# ====================
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
OBJS = sctnorm.o
SRC=sctnorm.c config.h

DSTPATH=$(BINPATH)
OUTPUT = sctnorm
LIBS=-lopt.1
SLIB=-lm

include $(MAKEBIN).$(SYSTEM)
