# Makefile for errlog library
# =========================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/superdarn
SRC=errlog.c
OBJS = errlog.o
LINK="1"
INC=${IPATH}/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = errlog
include $(MAKELIB).$(SYSTEM)










