# Makefile for cnvmap library
# ===========================
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis   
OBJS = cnvmap.o readmap.o writemap.o mapseek.o mapinx.o
SRC=  cnvmap.c readmap.c writemap.c mapseek.c mapinx.c
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)

OUTPUT = cnvmap
 

 





include $(MAKELIB).$(SYSTEM)
