# Makefile for RCDFMajority
# =========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis -I$(CDF_PATH)/include
IGNVER=1
OBJS = RCDFMajority.o
OUTPUT = RCDFMajority
LIBS= -lrcdf.1 -L$(CDF_PATH)/lib -lcdf 
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
