# Makefile for ConvertFreadFloat
# ===============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertFreadFloat.o
OUTPUT = ConvertFreadFloat
LIBS= -lrcnv.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
