# Makefile for radar library
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=rprm.c radar.c
OBJS = rprm.o radar.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = radar
LINK="1"



include $(MAKELIB).$(SYSTEM)
