# Makefile for XMLSetEnd
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = XMLSetEnd.o
OUTPUT = XMLSetEnd
LIBS=-lrxml.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
