# Makefile for XwinDisplayEvent
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinDisplayEvent.o
OUTPUT = XwinDisplayEvent
LIBS=-lrfbuf.1  
XLIB=-lxwin.1
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
