# Makefile for TimeYMDHMSToEpoch
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYMDHMSToEpoch.o
OUTPUT = TimeYMDHMSToEpoch
LIBS=-lrtime.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
