# Makefile for AACGMLoadCoef
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = AACGMLoadCoef.o
OUTPUT = AACGMLoadCoef
LIBS= -laacgm.1  
SLIB=-lm
 





include $(MAKEBIN).$(SYSTEM)
