# Makefile for sort library
# =========================
# Author: Angeline G. Burrell, NRL (2021)
# This is a U.S. government work and not under copyright protection in the U.S.
#
# Disclaimer: RST is licensed under GPL v3.0. Please visit 
#             <https://www.gnu.org/licenses/> to see the full license
#
# Modifications:

include $(MAKECFG).$(SYSTEM)

INCLUDE = -I../include
INC = $(IPATH)/general
DSTPATH = $(LIBPATH)
OUTPUT = sort

SRC = sort.c
OBJS = $(SRC:.c=.o)

LINK = "1"

include $(MAKELIB).$(SYSTEM)
