# Makefile for contour
# =====================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=contour.c 
OBJS = contour.o 
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = contour
LINK="1"

 

 















include $(MAKELIB).$(SYSTEM)
