# Makefile for fio library
# =========================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/superdarn
SRC=fio.c
OBJS = fio.o
LINK="1"
INC=${IPATH}/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = fio
include $(MAKELIB).$(SYSTEM)










