# Makefile for oldfit
# =================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC=fitreadinx.c fitopen.c fitread.c fitclose.c fitreadcurrent.c fitscan.c fitwrite.c fitseek.c fitstr.h fitversions.h fitreadinx.h
OBJS=fitreadinx.o  fitopen.o fitread.o fitclose.o fitreadcurrent.o fitscan.o fitwrite.o fitseek.o
INC=$(IPATH)/superdarn
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = oldfit


 

 















include $(MAKELIB).$(SYSTEM)
