# Makefile for OptionDump
# =======================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionDump.o
OUTPUT = OptionDump
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
