# Makefile for mkidlcoef
# ======================
# Author: R.J.Barnes
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis
OBJS = mkidlcoef.o
SRC=mkidlcoef.c
DSTPATH = $(BINPATH)
OUTPUT = mkidlcoef
LNK=$(ARC)
LIBS=-laacgm.1
SLIB=-lm

 
include $(MAKEBIN).$(SYSTEM)
