#  Makefile for astalg library
#  ===========================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/analysis

SRC = AstAlg_apparent_obliquity.c AstAlg_apparent_solar_longitude.c AstAlg_dday.c AstAlg_equation_of_time.c AstAlg_geometric_solar_longitude.c AstAlg_jde.c AstAlg_jde2calendar.c AstAlg_lunar_ascending_node.c AstAlg_mean_lunar_longitude.c AstAlg_mean_obliquity.c AstAlg_mean_solar_anomaly.c AstAlg_mean_solar_longitude.c AstAlg_nutation_corr.c AstAlg_solar_declination.c AstAlg_solar_right_ascension.c

OBJS = AstAlg_apparent_obliquity.o AstAlg_apparent_solar_longitude.o AstAlg_dday.o AstAlg_equation_of_time.o AstAlg_geometric_solar_longitude.o AstAlg_jde.o AstAlg_jde2calendar.o AstAlg_lunar_ascending_node.o AstAlg_mean_lunar_longitude.o AstAlg_mean_obliquity.o AstAlg_mean_solar_anomaly.o AstAlg_mean_solar_longitude.o AstAlg_nutation_corr.o AstAlg_solar_declination.o AstAlg_solar_right_ascension.o

INC = $(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = astalg
LINK="1"


 















include $(MAKELIB).$(SYSTEM)
