# Makefile for OptionPrintInfo
# ============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionPrintInfo.o
OUTPUT = OptionPrintInfo
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
