# Makefile for TimeJulianToYMDHMS
# ===============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYrsecToYMDHMS.o
OUTPUT = TimeYrsecToYMDHMS
LIBS=-lrtime.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
