#  Makefile for igrf library
#  ========================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/analysis
SRC = shval3.c shval3.h dihf.c interpshc.c interpshc.h extrapshc.c extrapshc.h \
    magcmp.c igrfcall.c getshc.c getshc.h  
OBJS = shval3.o dihf.o interpshc.o extrapshc.o magcmp.o igrfcall.o getshc.o
INC = $(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = igrf
LINK="1"


 















include $(MAKELIB).$(SYSTEM)
