# Makefile for fitacfex library
# ========================
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn

SRC = fitacfex.c
OBJS = fitacfex.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = fitacfex
include $(MAKELIB).$(SYSTEM)
