# Makefile for OldFitInxHeaderFwrite
# ==================================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
IGNVER=1
OBJS = OldFitInxHeaderFwrite.o
OUTPUT = OldFitInxHeaderFwrite
LIBS=-loldfit.1 -lrtime.1 -lrcnv.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
