# Makefile for SZAEqOfTime
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/imagery -I$(IPATH)/general 
IGNVER=1
DSTPATH=.
OBJS = SZAEqOfTime.o
OUTPUT = SZAEqOfTime
LIBS= -lsza.1 -lrtime.1 
SLIB=-lm
 
include $(MAKEBIN).$(SYSTEM)
