# Makefile for ConvertReadInt
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertReadInt.o
OUTPUT = ConvertReadInt
LIBS= -lrcnv.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
