# Makefile for XwinMakeWindow
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinMakeWindow.o
OUTPUT = XwinMakeWindow
LIBS=-lrfbuf.1 
XLIB=-lxwin.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
