# Makefile for xwin
# =================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(XPATH)/include

SRC=xwin.c
OBJS = xwin.o
INC=$(IPATH)/base
LINK="1"
DSTPATH=$(LIBPATH)

ifdef XPATH
OUTPUT=xwin
endif






include $(MAKELIB).$(SYSTEM)
