MODULE MLTDLM
DESCRIPTION MLTDLM
VERSION 1.0
SOURCE R.J.Barnes, JHU/APL
BUILD_DATE October 2010
FUNCTION MLTCONVERTYMDHMS 7 7
FUNCTION MLTCONVERTYRSEC 3 3 
FUNCTION MLTCONVERTEPOCH 2 2 





