MODULE RPOSDLM
DESCRIPTION RPOSDLM
VERSION 1.0
SOURCE R.J.Barnes (JHU/APL) & E.G.Thomas (Dartmouth)
BUILD_DATE October 2010
FUNCTION RADARLOAD 1 1
FUNCTION RADARLOADHARDWARE 1 1 KEYWORDS
FUNCTION RADARLOADTDIFF 1 1 KEYWORDS
FUNCTION RADAREPOCHGETSITE 2 2
FUNCTION RADARYMDHMSGETSITE 7 7
FUNCTION RADAREPOCHGETTDIFF 5 5
FUNCTION RADARYMDHMSGETTDIFF 10 10
FUNCTION RADARGETRADAR 2 2
FUNCTION RADARPOS 11 11 KEYWORDS
FUNCTION RADARPOSGS 11 11 KEYWORDS

