# Makefile for TimeEpochToYMDHMS
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeEpochToYMDHMS.o
OUTPUT = TimeEpochToYMDHMS
LIBS=-lrtime.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
