# Makefile for ConnexReadMem
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexReadMem.o
OUTPUT = ConnexReadMem
LIBS= -lcnx.1
SLIB= -lm
 
include $(MAKELIB).$(SYSTEM)
