# makefile for lmfit
#
#
include $(MAKECFG).$(SYSTEM)


INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis -I/data/fit/aj/cmpfit-1.2/
SRC = fitacfex2.c fitacfex2.h
OBJS = fitacfex2.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=fitacfex2
LINK="1"



include $(MAKELIB).$(SYSTEM)
