# Makefile for radarscan library
# ============================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = radarscan.c  
OBJS = radarscan.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = rscan


 

 















include $(MAKELIB).$(SYSTEM)
