# Makefile for grid library
# =========================== 
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = grid.c addgrid.c avggrid.c copygrid.c integrategrid.c mergegrid.c \
       readgrid.c writegrid.c sortgrid.c gridseek.c gridinx.c
OBJS = grid.o addgrid.o avggrid.o copygrid.o integrategrid.o mergegrid.o \
       readgrid.o writegrid.o sortgrid.o gridseek.o gridinx.o

INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = grd
 

 





include $(MAKELIB).$(SYSTEM)
