MODULE IQDLM
DESCRIPTION IQDLM
VERSION 1.0
SOURCE R.J.Barnes, JHU/APL
BUILD_DATE October 2010
FUNCTION IQREAD 5 5 
FUNCTION IQWRITE 5 5
FUNCTION IQLOADINX 2 2
FUNCTION IQSEEK 7 8 KEYWORDS
FUNCTION IQOPEN 1 1 KEYWORDS
FUNCTION IQCLOSE 1 1





