MODULE OLDFITDLM
DESCRIPTION OLDFITDLM
VERSION 1.0
SOURCE R.J.Barnes, JHU/APL
BUILD_DATE October 2010
FUNCTION OLDFITREAD 3 3
FUNCTION OLDFITWRITE 3 3
FUNCTION OLDFITSEEK 7 7 KEYWORDS
FUNCTION OLDFITOPEN 1 2
FUNCTION OLDFITCLOSE 1 1
FUNCTION OLDFITWRITEHEADER 3 3
FUNCTION OLDFITINXWRITE 4 4
FUNCTION OLDFITINXWRITEHEADER 2 2
FUNCTION OLDFITINXOPEN 1 1
FUNCTION OLDFITINXCLOSE 3 3

