# Makefile for radarshell library
# =========================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/superdarn
SRC=radarshell.c
OBJS = radarshell.o
LINK="1"
INC=${IPATH}/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = radarshell
include $(MAKELIB).$(SYSTEM)










