# Makefile for XwinFrameBufferWindow
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinFrameBufferWindow.o
OUTPUT = XwinFrameBufferWindow
LIBS=-lrfbuf.1  
XLIB=-lxwin.1
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
