# Makefile for ppmd
# ==================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=ppmd.c
OBJS = ppmd.o
SRC=hlpstr.h errstr.h ppmd.c
OBJS = ppmd.o
DSTPATH = $(BINPATH)
OUTPUT = ppmd
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lpng -lm 

 

include $(MAKEBIN).$(SYSTEM)
