# Makefile for ConvertBitOrder
# ============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertBitOrder.o
OUTPUT = ConvertBitOrder
LIBS= -lrcnv.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
