# Makefile for FrameBufferDBFree
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = FrameBufferDBFree.o
OUTPUT = FrameBufferDBFree
LIBS=-limagedb.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
