# Makefile for ConnexRead
# =======================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexRead.o
OUTPUT = ConnexRead
LIBS= -lcnx.1
SLIB= -lm
 
include $(MAKELIB).$(SYSTEM)
