# Makefile for Frame Buffer Library
# =================================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=imagedb.c
OBJS=imagedb.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = imagedb
LINK="1"

















include $(MAKELIB).$(SYSTEM)
