# Makefile for XwinFreeWidnow
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinFreeWindow.o
OUTPUT = XwinFreeWindow
LIBS=-lrfbuf.1  
XLIB=-lxwin.1
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
