# Makefile for radar library
# ========================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = smrread.c smrseek.c smrscan.c smrwrite.c

OBJS = smrread.o smrseek.o smrscan.o smrwrite.o 
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = smr
LINK="1"


 

 















include $(MAKELIB).$(SYSTEM)
