# Makefile for ConnexWriteMem
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexWriteMem.o
OUTPUT = ConnexWriteMem
LIBS= -lcnx.1
SLIB= -lm
 
include $(MAKELIB).$(SYSTEM)
