# Makefile for ACFex library
# ========================
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn

SRC = acfex.c
OBJS = acfex.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = acfex
include $(MAKELIB).$(SYSTEM)
