# Makefile for ConvertWriteShort
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConvertWriteShort.o
OUTPUT = ConvertWriteShort
LIBS= -lrcnv.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
