# Makefile for TimeYMDHMSToYrsec
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeYMDHMSToYrsec.o
OUTPUT = TimeYMDHMSToYrsec
LIBS=-lrtime.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
