# Makefile for gtable library
# =========================== 
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
SRC = gtable.c 
OBJS = gtable.o 
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = gtable
 

 





include $(MAKELIB).$(SYSTEM)
