MODULE CNVMAPDLM
DESCRIPTION CNVMAPDLM
VERSION 1.0
SOURCE R.J.Barnes, JHU/APL
BUILD_DATE October 2010
FUNCTION CNVMAPREAD 7 7
FUNCTION CNVMAPWRITE 7 7
FUNCTION CNVMAPLOADINX 2 2
FUNCTION CNVMAPSEEK 7 8 KEYWORDS
FUNCTION CNVMAPOPEN 1 1 KEYWORDS
FUNCTION CNVMAPCLOSE 1 1





