#  Makefile for astalg library
#  ===========================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/analysis

SRC = astalglib.c
OBJS = astalglib.o
INC = $(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = astalg
LINK="1"

include $(MAKELIB).$(SYSTEM)

