# Makefile for XwinShowWindow
# =============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 
IGNVER=1
OBJS = XwinShowWindow.o
OUTPUT = XwinShowWindow
LIBS=-lrfbuf.1 
XLIB-lxwin.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
