# Makefile for oldgtablewrite library
# =================================== 
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
SRC = oldgtablewrite.c 
OBJS = oldgtablewrite.o 
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = oldgtabw
 

 





include $(MAKELIB).$(SYSTEM)
