# Makefile for Shared Memory Library
# ==================================
# by J.Spaleta & R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base 

SRC = shmem.c
OBJS = shmem.o
INC=$(IPATH)/base
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = shmem

include $(MAKELIB).$(SYSTEM)
