# Makefile for OptionFree
# ======================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = OptionFree.o
OUTPUT = OptionFree
LIBS= -lopt.1
SLIB= -lm
 





include $(MAKELIB).$(SYSTEM)
