# Makefile for cmpfit library
# ===========================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis

SRC = mpfit.c mpfit.h
OBJS = mpfit.o

INC=$(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = cmpfit
LINK="1"

include $(MAKELIB).$(SYSTEM)

