# Makefile for map library
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=transform.c clip.c wrap.c load.c gcircle.c tfunc.c plot.c
OBJS =transform.o clip.o wrap.o load.o gcircle.o tfunc.o plot.o
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = rmap
LINK="1"

















include $(MAKELIB).$(SYSTEM)
