# Makefile for DataMapMake
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = DataMapMake.o
OUTPUT = DataMapMake
LIBS=-ldmap.1 -lrcnv.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
