# Makefile for FrameBufferFontDBFree
# ==================================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = FrameBufferFontDBFree.o
OUTPUT = FrameBufferFontDBFree
LIBS=-lfontdb.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
