# Makefile for script library
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=rscript.c rscriptHTML.c
OBJS = rscript.o rscriptHTML.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = rscript
LINK="1"

















include $(MAKELIB).$(SYSTEM)
