# Makefile for raster_lib
# =====================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/general
SRC=raster.c 
OBJS = raster.o 
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = raster
LINK="1"

 

 















include $(MAKELIB).$(SYSTEM)
