# Makefile for filter library
# ============================== 
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
SRC = filter.c bound.c checkops.c
OBJS = filter.o bound.o checkops.o
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = filter


 

 















include $(MAKELIB).$(SYSTEM)
