MODULE FITDLM
DESCRIPTION FITDLM
VERSION 1.0
SOURCE R.J.Barnes, JHU/APL
BUILD_DATE October 2010
FUNCTION FITREAD 3 3
FUNCTION FITWRITE 3 3
FUNCTION FITLOADINX 2 2
FUNCTION FITSEEK 7 8 KEYWORDS
FUNCTION FITOPEN 1 1 KEYWORDS
FUNCTION FITCLOSE 1 1




