# Makefile for sza
# ================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis \
        -I$(IPATH)/imagery
SRC =  sza.c   
OBJS = sza.o
INC=$(IPATH)/imagery
LINK="1"

DSTPATH=$(LIBPATH)
OUTPUT = sza


 

 





include $(MAKELIB).$(SYSTEM)
