# Makefile for oldcnvmap library
# ==============================
# by R.J.Barnes
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis   
OBJS = readmap.o writemap.o
SRC=  readmap.c writemap.c
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)

OUTPUT = oldcnvmap
 

 





include $(MAKELIB).$(SYSTEM)
