# Makefile for option library
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=option.c printinfo.c 
OBJS = option.o printinfo.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = opt
LINK="1"

















include $(MAKELIB).$(SYSTEM)
