# Makefile for TimeReadClock
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/general 
IGNVER=1
OBJS = TimeReadClock.o
OUTPUT = TimeReadClock
LIBS=-lrtime.1 
SLIB=-lm
 
include $(MAKELIB).$(SYSTEM)
