# Makefile for convert library
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=convert.c
INC=$(IPATH)/base
OBJS = convert.o
DSTPATH=$(LIBPATH)
OUTPUT = rcnv
LINK="1"

















include $(MAKELIB).$(SYSTEM)
