# Makefile for time library
# =========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general
SRC=rfile.c
OBJS = rfile.o
INC=$(IPATH)/general
DSTPATH=$(LIBPATH)
OUTPUT = rfile
LINK="1"

















include $(MAKELIB).$(SYSTEM)
