# Makefile for rmsgsnd library
# =========================== 
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn
SRC=rmsgsnd.c
OBJS = rmsgsnd.o
LINK="1"
INC=${IPATH}/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = rmsgsnd
include $(MAKELIB).$(SYSTEM)

 















