#  Makefile for igrf_v2 library
#  ============================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis
SRC = igrflib.c
OBJS = igrflib.o
INC = $(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = igrf_v2
LINK="1"

include $(MAKELIB).$(SYSTEM)

