# Makefile for xmltoppmx
# ======================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=xmltoppmx.c
OBJS = xmltoppmx.o
SRC=hlpstr.h errstr.h xmltoppmx.c
OBJS = xmltoppmx.o
DSTPATH = $(BINPATH)
OUTPUT = xmltoppmx
LIBS=-lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lpng -lm

include $(MAKEBIN).$(SYSTEM)
