# Makefile for gtablewrite library
# ================================ 
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn 
SRC = gtablewrite.c 
OBJS = gtablewrite.o 
INC=$(IPATH)/superdarn
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = gtabw
 
include $(MAKELIB).$(SYSTEM)
