# Makefile for FrameBufferText
# ========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general 
IGNVER=1
OBJS = FrameBufferText.o
OUTPUT = FrameBufferText
LIBS=-lrfbuf.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
