# Makefile for ppmxd
# ==================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=ppmxd.c
OBJS = ppmxd.o
SRC=hlpstr.h errstr.h ppmxd.c
OBJS = ppmxd.o
DSTPATH = $(BINPATH)
OUTPUT = ppmxd
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1
XLIB=-lxwin.1
SLIB= -lpng -lm 

 

include $(MAKEBIN).$(SYSTEM)
