# Makefile for rmsgrcv library
# =========================== 
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/superdarn
SRC=rmsgrcv.c
OBJS = rmsgrcv.o
LINK="1"
INC=${IPATH}/superdarn
DSTPATH=$(LIBPATH)
OUTPUT = rmsgrcv
include $(MAKELIB).$(SYSTEM)
















