# Makefile for fitacfex library
# ========================
# by R.J.Barnes
#

include $(MAKECFG).$(SYSTEM)


INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(USR_IPATH)/superdarn

SRC = fitacfex.c 
OBJS = fitacfex.o
INC=$(USR_IPATH)/superdarn
LINK="1"
DSTPATH=$(USR_LIBPATH)
OUTPUT = fitacfex
include $(MAKELIB).$(SYSTEM)



