# Makefile for ConnexOpen
# =======================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexOpen.o
OUTPUT = ConnexOpen
LIBS= -lcnx.1
SLIB= -lm
 
include $(MAKELIB).$(SYSTEM)
