# Makefile for PostScriptEndDocument
# ==================================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn
IGNVER=1
OBJS = PostScriptEndDocument.o
OUTPUT = PostScriptEndDocument
LIBS=-lrps.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
