#  Makefile for mlt library
#  ===========================
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis

SRC = mlt.c
OBJS= mlt.o

INC = $(IPATH)/analysis
DSTPATH=$(LIBPATH)
OUTPUT = mlt
LINK="1"


 















include $(MAKELIB).$(SYSTEM)
