# Makefile for Frame Buffer Library
# =================================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=fontdb.c

OBJS=fontdb.o
INC=$(IPATH)/base
DSTPATH=$(LIBPATH)
OUTPUT = fontdb
LINK="1"

















include $(MAKELIB).$(SYSTEM)
