# Makefile for poly
# =================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/general
SRC=poly.c isect.c
OBJS =  poly.o isect.o
INC=$(IPATH)/general
LINK="1"
DSTPATH=$(LIBPATH)
OUTPUT = poly

include $(MAKELIB).$(SYSTEM)
