# Makefile for ppmtoxml
# =====================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=ppmtoxml.c
OBJS = ppmtoxml.o
SRC=hlpstr.h errstr.h ppmtoxml.c
OBJS = ppmtoxml.o
DSTPATH = $(BINPATH)
OUTPUT = ppmtoxml
LIBS=-lrfbuf.1 -lrxml.1 -lopt.1 
SLIB= -lpng -lm


 















include $(MAKEBIN).$(SYSTEM)
