# Makefile for convert library
# ===========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)
INCLUDE=-I$(IPATH)/base
SRC=
OBJS = 
INC=$(IPATH)/base

DSTPATH=$(LIBPATH)
OUTPUT = 
LINK="1"

















include $(MAKELIB).$(SYSTEM)
