MODULE AACGMDLM
DESCRIPTION AACGMDLM
VERSION 2.0
SOURCE R.J.Barnes (JHU/APL) & E.G.Thomas (Dartmouth)
BUILD_DATE MAY 2017
FUNCTION AACGMINIT 1 1
FUNCTION AACGMLOADCOEF 1 1
FUNCTION AACGMCONVERT 6 6 KEYWORDS
FUNCTION AACGM_V2_GETDATETIME 1 1 KEYWORDS
FUNCTION AACGM_V2_SETDATETIME 1 6
FUNCTION AACGM_V2_SETNOW 0 0
FUNCTION AACGM_V2_CONVERT 6 6 KEYWORDS



