# Makefile for SZAAngle
# =====================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/imagery -I$(IPATH)/general 
IGNVER=1
OBJS = SZAAngle.o
DSTPATH=.
OUTPUT = SZAAngle
LIBS= -lsza.1 -lrtime.1 
SLIB=-lm
 
include $(MAKEBIN).$(SYSTEM)
