# Makefile for ConnexWriteIP
# ==========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = ConnexWriteIP.o
OUTPUT = ConnexWriteIP
LIBS= -lcnx.1
SLIB= -lm
 
include $(MAKELIB).$(SYSTEM)
