# makefile for lmfit
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis
SRC = lmfit.c lmfit.h
OBJS = lmfit.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=lmfit
LINK="1"



include $(MAKELIB).$(SYSTEM)
