MODULE SNDDLM
DESCRIPTION SNDDLM
VERSION 1.0
SOURCE E.G.Thomas, Dartmouth College
BUILD_DATE June 2020
FUNCTION SNDREAD 2 2
FUNCTION SNDWRITE 2 2
FUNCTION SNDSEEK 6 7 KEYWORDS
FUNCTION SNDOPEN 1 1 KEYWORDS
FUNCTION SNDCLOSE 1 1

