# Makefile for FrameBufferDBFind
# ==============================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
IGNVER=1
OBJS = FrameBufferDBFind.o
OUTPUT = FrameBufferDBFind
LIBS=-limagedb.1 -lrfbuf.1 -lrxml.1
SLIB=-lm
include $(MAKELIB).$(SYSTEM)
