# Makefile for pngtoppmx
# ======================
# Author: R.J.Barnes
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base
SRC=pngtoppmx.c
OBJS = pngtoppmx.o
SRC=hlpstr.h errstr.h pngtoppmx.c
OBJS = pngtoppmx.o
DSTPATH = $(BINPATH)
OUTPUT = pngtoppmx
LIBS=-lrxml.1 -lrfbuf.1 -lopt.1 
SLIB= -lpng -lm

include $(MAKEBIN).$(SYSTEM)
