# makefile for sim_data
#
#
include $(MAKECFG).$(SYSTEM)



INCLUDE= -I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/superdarn -I$(IPATH)/analysis
SRC = sim_data.c sim_data.h
OBJS = sim_data.o
INC=$(IPATH)/superdarn
DSTPATH=$(LIBPATH)
OUTPUT=sim_data
LINK="1"



include $(MAKELIB).$(SYSTEM)

