# Makefile for aacgm_v2 library
# =============================
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/base -I$(IPATH)/general -I$(IPATH)/analysis
SRC = aacgmlib_v2.c
OBJS = aacgmlib_v2.o
INC=$(IPATH)/analysis
DSTPATH=$(LIBPATH)
LINK="1"
OUTPUT = aacgm_v2

include $(MAKELIB).$(SYSTEM)

