# Makefile for AACGMConvert
# =========================
# by R.J.Barnes
#
#
include $(MAKECFG).$(SYSTEM)

INCLUDE=-I$(IPATH)/analysis 
IGNVER=1
OBJS = AACGMConvert.o
OUTPUT = AACGMConvert
LIBS= -laacgm.1  
SLIB=-lm
 





include $(MAKEBIN).$(SYSTEM)
